trigger:
  branches:
    include:
      - "*"

pool:
  name: Selfhosted
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    displayName: "Use .NET SDK 8.x"
    inputs:
      packageType: "sdk"
      version: "8.x"
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: NuGetToolInstaller@1
    displayName: "Install Nugets"
    inputs:
      versionSpec: "5.8.0"

  - task: DotNetCoreCLI@2
    displayName: "Restore dependencies"
    inputs:
      command: "restore"
      projects: "HelloWorldDevOps.sln"
      feedsToUse: "select"

  - task: DotNetCoreCLI@2
    displayName: "Build project"
    inputs:
      command: "build"
      projects: "SendRequests.console/HelloWorldDevOps.csproj"

  - script: |
      dotnet test SendRequests.Tests/SendRequests.Tests.csproj --logger "trx;LogFileName=$(Build.ArtifactStagingDirectory)/TestResults.xml" --results-directory "$(Build.ArtifactStagingDirectory)"
    displayName: "Run tests"

  - script: |
      if [ -f "$(Build.ArtifactStagingDirectory)/TestResults.xml" ]; then
        echo "Test results file found."
        chmod 644 $(Build.ArtifactStagingDirectory)/TestResults.xml
      else
        echo "Test results file NOT found."
      fi
    displayName: "Check Test Results File"
    condition: always()

  - script: ls -R "$(Build.ArtifactStagingDirectory)"
    displayName: "List Artifact Staging Directory"
    condition: always()

  - task: PublishTestResults@2
    condition: always()
    displayName: "Publish test results"
    inputs:
      testResultsFiles: "$(Build.ArtifactStagingDirectory)/TestResults.xml"
      testRunTitle: "xUnit Tests"
      publishRunAttachments: true