trigger:
  branches:
    include:
      - "*"

pool:
  name: Selfhosted
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    displayName: "Use .NET SDK 8.x"
    inputs:
      packageType: "sdk"
      version: "8.x"
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: NuGetToolInstaller@1
    displayName: "Install Nugets"
    inputs:
      versionSpec: "5.8.0"

  - task: DotNetCoreCLI@2
    displayName: "Restore dependencies"
    inputs:
      command: "restore"
      projects: "HelloWorldDevOps.sln"
      feedsToUse: "select"

  - task: DotNetCoreCLI@2
    displayName: "Build project"
    inputs:
      command: "build"
      projects: "SendRequests.console/HelloWorldDevOps.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Run tests"
    inputs:
      command: "test"
      projects: "SendRequests.Tests/SendRequests.Tests.csproj"
      arguments: '--logger "trx;LogFileName=$(Agent.TempDirectory)/TestResults.xml" --results-directory "$(Agent.TempDirectory)"'

  - script: ls -R "$(Agent.TempDirectory)"
    displayName: "List Temp Directory"
    condition: always()

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    displayName: "Publish test results"
    inputs:
      testResultsFiles: "$(Agent.TempDirectory)/TestResults.xml"
      testRunTitle: "xUnit Tests"
